
server.port: ${PORT:0}

spring:
  config:
    import: optional:file:../env/.cloudenv.yaml
  pulsar:
    producer:
      cache:
        expire-after-access: 10s
demo-topic-name: "persistent://public/default/sps-gae-imperative-demo-topic"

---
spring:
  config:
    activate:
      on-profile: "datastax"
  pulsar:
    client:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authentication:
        token: ${DATASTAX_AUTH_TOKEN:<auth-token-goes-here>}
      service-url: ${DATASTAX_BROKER_URL:<broker-service-url-goes-here>}
    administration:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authentication:
        token: ${DATASTAX_AUTH_TOKEN:<auth-token-goes-here>}
      service-url: ${DATASTAX_ADMIN_URL:<admin-service-url-goes-here>}
demo-topic-name: "persistent://sps-tenant1/sps-ns1/sps-gae-imperative-demo-topic"

---
spring:
  config:
    activate:
      on-profile: "streamnative"
  pulsar:
    client:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authentication:
        token: ${STREAM_NATIVE_AUTH_TOKEN:<auth-token-goes-here>}
      service-url: ${STREAM_NATIVE_BROKER_URL:<broker-service-url-goes-here>}
    administration:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authentication:
        token: ${STREAM_NATIVE_AUTH_TOKEN:<auth-token-goes-here>}
      service-url: ${STREAM_NATIVE_ADMIN_URL:<admin-service-url-goes-here>}
demo-topic-name: "persistent://sps-tenant1/sps-ns1/sps-gae-imperative-demo-topic"
