
server.port: ${PORT:0}

spring:
  pulsar:
    producer:
      cache:
        expire-after-access: 10s
demo-topic-name: "persistent://public/default/sps-gae-reactive-demo-topic"

---
spring:
  config:
    activate:
      on-profile: "datastax"
  pulsar:
    client:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authentication:
        token: <auth-token>
      service-url: <service-url>
    administration:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authentication:
        token: <auth-token>
      service-url: <service-url>
demo-topic-name: "persistent://sps-tenant1/sps-ns1/sps-gae-reactive-demo-topic"


---
spring:
  config:
    activate:
      on-profile: "streamnative"
  pulsar:
    client:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authentication:
        token: <auth-token>
      service-url: <service-url>
    administration:
      auth-plugin-class-name: org.apache.pulsar.client.impl.auth.AuthenticationToken
      authentication:
        token: <auth-token>
      service-url: <service-url>
demo-topic-name: "persistent://sps-tenant1/sps-ns1/sps-gae-reactive-demo-topic"
